; Create a bootable image on disk A: of CP/M with CCPZ
; Based on original Digital Research source for BDOS
; CCP is replaced by CCPZ a Z80 version of CP/M CCP
; Required sources are CFGCCPZ.LIB, MOVER.MAC, CCPZ.MAC, BDOS.MAC, CBIOSX.MAC
; Required programs: M80.COM, L80.COM, DDT.COM, BOOT.COM, BOOTGEN.COM
XSUB
; get correct configuration
PIP MEMCFG.LIB=CFGCCPZ.LIB
; create MOVER.COM
M80 =MOVER/M
L80 MOVER,MOVER/N/E
ERA MOVER.REL
; create CCPZ.COM
M80 =CCPZ/M
L80 CCPZ,CCPZ/N/E
ERA CCPZ.REL
; create BDOS.COM
M80 =BDOS/M
L80 BDOS,BDOS/N/E
ERA BDOS.REL
; create CBIOSX.COM
M80 =CBIOSX/M
L80 CBIOSX,CBIOSX/N/E
ERA CBIOSX.REL
; put pieces together
DDT
F100 5C00 0
IMOVER.COM
R0000
ICCPZ.COM
R0900
IBDOS.COM
R1100
ICBIOSX.COM
R1F00
G0
; create boot file
SAVE 44 CPMZBOOT.COM
ERA MOVER.COM
ERA CCPZ.COM
ERA BDOS.COM
ERA CBIOSX.COM
ERA MEMCFG.LIB
; now perform a cold boot to get rid of XSUB
; this restores the original BIOS jump vector which is required by BOOTGEN
BOOT
; write boot file to reserved tracks, must be last command
BOOTGEN CPMZBOOT.COM A:
